### ISSUE TITLE
Can't make the plugin working on QGIS2.99

### ISSUE THREAD

**Issue by epzt** [ArteliaTelemac/PostTelemac#14]
Dear developers,
I'm under QGIS 2.99 dev version and installed the plugin though the official extension manager of QGIS.
When installed, a click on PostTelemac produce following errors:
TypeError: QgsCoordinateTransform(): arguments did not match any overloaded call:   overload 1: too many arguments   overload 2: not enough arguments   overload 3: not enough arguments   overload 4: not enough arguments   overload 5: argument 1 has unexpected type 'QgsCoordinateReferenceSystem' 
Traceback (most recent call last):
  File "/home/epoizot/.local/share/QGIS/QGIS3/profiles/default/python/plugins/PostTelemac/PostTelemac.py", line 261, in run
    self.slf[len(self.slf)-1].setRealCrs(self.iface.mapCanvas().mapSettings().destinationCrs())   #to prevent weird bug with weird crs
  File "/home/epoizot/.local/share/QGIS/QGIS3/profiles/default/python/plugins/PostTelemac/meshlayer/post_telemac_pluginlayer.py", line 409, in setRealCrs
    self.xform  = qgis.core.QgsCoordinateTransform(self.realCRS, qgis.utils.iface.mapCanvas().mapSettings().destinationCrs())
TypeError: QgsCoordinateTransform(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: not enough arguments
  overload 3: not enough arguments
  overload 4: not enough arguments
  overload 5: argument 1 has unexpected type 'QgsCoordinateReferenceSystem'

Version de Python : 3.6.3 (default, Oct  3 2017, 21:45:48) [GCC 7.2.0] 
Version de QGIS : 2.99.0-Master Master, fcbf4cb 

Chemin Python :
/usr/share/qgis/python/plugins/processing
/usr/share/qgis/python
/home/epoizot/.local/share/QGIS/QGIS3/profiles/default/python
/home/epoizot/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.6/dist-packages
/home/epoizot/.local/share/QGIS/QGIS3/profiles/default/python

How can I resolve that ?
Thanks

**Comment by geraldineCA** [comment]
Hello,
 I have the same problem:


Version de QGIS     3.2.2-Bonn

Révision du code        26842169e9



2018-09-10T10:05:48     WARNING    Traceback (most recent call last):
              File "C:/Users/geraldine.cara/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\PostTelemac\PostTelemac.py", line 261, in run
              self.slf[len(self.slf)-1].setRealCrs(self.iface.mapCanvas().mapSettings().destinationCrs()) #to prevent weird bug with weird crs
              File "C:/Users/geraldine.cara/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\PostTelemac\meshlayer\post_telemac_pluginlayer.py", line 409, in setRealCrs
              self.xform = qgis.core.QgsCoordinateTransform(self.realCRS, qgis.utils.iface.mapCanvas().mapSettings().destinationCrs())
             TypeError: QgsCoordinateTransform(): arguments did not match any overloaded call:
              overload 1: too many arguments
              overload 2: not enough arguments
              overload 3: not enough arguments
              overload 4: not enough arguments
              overload 5: argument 1 has unexpected type 'QgsCoordinateReferenceSystem'

Can you help me, please ?
Thanks.

**Comment by cb14G** [comment]
Hello,

I also get the same error with the latest release of QGIS:
QGIS version 3.4.2-Madeira

"
2018-12-18T12:01:16     WARNING    Traceback (most recent call last):
              File "C:/Users/cb14/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\PostTelemac\PostTelemac.py", line 261, in run
              self.slf[len(self.slf)-1].setRealCrs(self.iface.mapCanvas().mapSettings().destinationCrs()) #to prevent weird bug with weird crs
              File "C:/Users/cb14/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\PostTelemac\meshlayer\post_telemac_pluginlayer.py", line 409, in setRealCrs
              self.xform = qgis.core.QgsCoordinateTransform(self.realCRS, qgis.utils.iface.mapCanvas().mapSettings().destina/ionCrs())
             TypeError: QgsCoordinateTransform(): arguments did not match any overloaded call:
              overload 1: too many arguments
              overload 2: not enough arguments
              overload 3: not enough arguments
              overload 4: not enough arguments
              overload 5: argument 1 has unexpected type 'QgsCoordinateReferenceSystem'
"

From the Telemac forum, I read this may be an issue of QGIS version, and that it works ok with v. 2.18. 

Could someone tell if this useful plugin will be ported/updated to the latest QGIS version please?
Thanks

**Comment by ccoulet** [comment]
Hi
It's not in the immediate plans to update the plugin, due to lack of time and funding and also because LTR is version 2.18...
Nevertheless, this will be possibly done in the beginning of 2019 as the next LTR version will probably be 3.4.x
Regards

**Comment by nicogodet** [comment]
Hello,
Any news on the update of the plugin to support Qgis 3.4.X or 3.10.X ?
Regards

**Comment by patricev** [comment]
Hello, 
We are working on the update of posttelamac, with mdal in the back-end. We think the update may be operational for the end of S1 2020 with QGis 3.10.
Sorry for the  annoyance 
Regards

**Comment by julimi26** [comment]
Hello, 

is the update already released? I got the same issue. I just installed the posttelemac plug-in for my qgis 3.12. bucuresti and I get the same error messages. 

Greetings!

**Comment by nicogodet** [comment]
@jumi26 You need to download the plugin from github and copy manually the subfolder PostTelemac in your plugin directory

It's not an official release but it works

**Comment by julimi26** [comment]
Great! It worked out!
